name: Upload Python Package

on: push
jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      
      - name: Checkout Google Chrome
        uses: nanasess/setup-chromedriver@v1

      - name: Install Google
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools twine wheel pytest flake8
          pip install -r requirements.txt

      - name: Linkt with flake8
        run: |
          flake8 easy_selenium

      - name: Test with pytest
        run: pytest lucd/tests/ --disable-warnings

      - name: Build and publish
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          twine upload dist/* -u __token__ -p "${{ secrets.PYPI_API_TOKEN }}" --skip-existing --verbose